### ISSUE TITLE
How to assess thread safety of any given librpma API function

### ISSUE THREAD

**Issue by janekmi** [pmem/rpma#1007]
If you are just curious what librpma API call is thread-safe and which is not I strongly recommend reading the documentation: https://pmem.io/rpma/manpages/v0.9.0/librpma.7.html#thread-safety

But let's assume you are a good egg wanting to help us prove the thread-safety of the librpma API calls. If it is the case I want to collect here all required information that may be useful for guiding you through the process.

# Adding missing suppressions

It is expected that libibverbs and librdmacm may require providing additional suppressions. The role of these suppressions in the whole process is yet to be described.

To add the missing suppressions, follow these steps:

1. Push a commit with the change in file helpers.cmake:
    - Add the `--gen-suppressions=all` command to these lines.
        - https://github.com/pmem/rpma/blob/master/tests/cmake/helpers.cmake#L108
        - https://github.com/pmem/rpma/blob/master/tests/cmake/helpers.cmake#L111
    - As follows:

```cmake
   set(TRACE valgrind --error-exitcode=99 --tool=helgrind --gen-suppressions=all --suppressions=${TEST_ROOT_DIR}/helgrind.supp)
   set(ENV{LIBRPMA_TRACER_HELGRIND} 1)
elseif(${TRACER} STREQUAL drd)
   set(TRACE valgrind --error-exitcode=99 --tool=drd --gen-suppressions=all --suppressions=${TEST_ROOT_DIR}/drd.supp)
```

2. On Circle Ci open the build log.
3. Modify the resulting suppressions and add them to the appropriate files:
    - https://github.com/pmem/rpma/blob/master/tests/drd.supp
    - https://github.com/pmem/rpma/blob/master/tests/helgrind.supp

## A suppression example

Suppression fragment obtained from Circle CI:

```
{
   <insert_a_suppression_name_here>
   drd:ConflictingAccess
   fun:strlen
   fun:__tzstring
   fun:__tzfile_compute
   fun:__tz_convert
   fun:__vsyslog_internal
   fun:syslog
   fun:rpma_log_default_function
   fun:rpma_ep_listen
   fun:thread
   fun:mtt_thread_main
   obj:/usr/lib/x86_64-linux-gnu/valgrind/vgpreload_drd-amd64-linux.so
   fun:start_thread
}
```

A ready suppression:

```
{
   Race while reading the name of time zone ("GMT").
   drd:ConflictingAccess
   ...
   fun:__tzfile_compute
   fun:__tz_convert
   fun:__vsyslog_internal
   fun:syslog
   fun:rpma_log_default_function
   ...
}
```

Stay tuned for more.

**Comment by janekmi** [comment]
# librpma API calls and their MT-tests coverage/status

## Seemingly not-thread-safe

**Note**: Some of these functions even if not intrinsically not-thread-safe are not thread-rational e.g. there is no point in allowing writing concurrently the same value by multiple threads since no one knows what the result will be.

- rpma_log_set_function
- rpma_log_set_threshold

## Potentially thread-safe

**Note**: This API calls tree below show the asssumed best order of implementation when the API calls being deeper somehow depends / requires the API calls being higher e.g. before calling `rpma_peer_delete()` you have to think about `rpma_peer_new()`.

- ⬜ `rpma_utils_conn_event_2str()`
- ☑️ `rpma_utils_get_ibv_context()`
    - ✴️ `rpma_utils_ibv_context_is_odp_capable()`
- ⬜ `rpma_err_2str()`
- ⬜ `rpma_log_get_threshold()`
- ✴️ `rpma_peer_new()`
    - ⬜ `rpma_peer_delete()`
        - using different peer objects
        - ⬜ `rpma_mr_reg()`
            - using the same peer object
            - ⬜ `rpma_mr_dereg()`
                - using different mr objects
            - ⬜ `rpma_mr_get_ptr()`
                - the same mr for all threads
            - ⬜ `rpma_mr_get_size()`
                - the same mr for all threads
            - ⬜ `rpma_mr_get_descriptor_size()`
                - the same mr for all threads
                - ⬜ `rpma_mr_get_descriptor()`
                    - using the same mr object
                    - ⬜ `rpma_mr_remote_from_descriptor()`
                        - using the same mr object
                        - ⬜ `rpma_mr_remote_delete()`
                            - using different mr_remote objects
                            - ⬜ `rpma_mr_remote_get_flush_type()`
                                - using the same mr_remote
                            - ⬜ `rpma_mr_remote_get_size()`
                                - using the same mr_remote

- ✴️ `rpma_peer_cfg_from_descriptor()`

Stay tuned for more. :-)

## Key

⬜ - yet to be done
☑️ - MT-test is ready but thread safety not yet fully assessed
✴️ - MT-test is ready but requires rework
❎ - thread-safety assessed negatively
✅ - MT-test ready and thread-safety fully assessed and confirmed

**Comment by grom72** [comment]
Thread safety analysis has been moved to [THREAD_SAFETY.md](https://github.com/pmem/rpma/blob/master/THREAD_SAFETY.md)
