### ISSUE TITLE
Is it better to do the RDMA performance test by fio?

### ISSUE THREAD

**Issue by yangx-jy** [pmem/rpma#1143]
@janekmi @ldorau @grom72 

I found that both perftest and fio can do the RDMA performance test, but perftest and fio provides different logic to running test.
Is it easy/fair for user to compare the performance for RDMA and RPMA by using the same fio benchmark?

**Comment by janekmi** [comment]
You have missed @osalyk . :-)

I am happy to learn what you have found out. Please provide more details.

**Comment by hualongfeng** [comment]
Do you have performance data?
I write a simple client-server code. When I use the `rpma_write` operation to send 1G data, only 64byte is sent for each `rpma_write` operation. The final effect is that I ran all night and the operation has not been sent yet. Is it normal?

**Comment by grom72** [comment]
@hualongfeng  Do you mean https://github.com/hualongfeng/rpma_demo example?
Do you still have performance problems?

**Comment by grom72** [comment]
Hi @yangx-jy,
we use perftest mainly to verify that our fio engines work properly (some kind of sanity check).
The perftest gives the baseline (max BW etc). It will be removed in the future from the performance report when we collect more data and build some logic to compare perftest and rpma results automatically.

**Comment by janekmi** [comment]
@hualongfeng here you can find more performance results: https://pmem.io/rpma/reports/index.html :-)
