### ISSUE TITLE
Remote persistence issue of RDMA read

### ISSUE THREAD

**Issue by StephenQi** [pmem/rpma#1159]
### Discussed in https://github.com/pmem/rpma/discussions/1158

<div type='discussions-op-text'>

<sup>Originally posted by **StephenQi** July 23, 2021</sup>
 **In case the client turns off DDIO and reads data using RDMA read directly from the remote NVM of the server to the local NVM region, does the client need additional operations to ensure persistence?**</div>

**Comment by grom72** [comment]
It is RNIC design related.
If RNIC ensures that write operation is completed in memory before completion is generated no additional action is needed.
