### ISSUE TITLE
ibv_reg_mr fails with pmem in virtual environment

### ISSUE THREAD

**Issue by baru64** [pmem/rpma#1197]
I'm trying to use rpma and rpmem examples and always fail to register a MR in persistent memory.
My setup is 2 virtualbox VMs with fedora 33, rxe and kernel memmap option. I can use rdma with normal memory, but ibv_reg_mr always fails with -12 on pmem.
Example 03 with fsdax mode and 1M file on ext4 fs:
```
[vagrant@node2 03-read-to-persistent]$ ./server 192.168.33.11 2000 /pmem/file1 
Aug 13 17:14:20.751250 [145661] *NOTE*  ep.c:  92: rpma_ep_listen: Waiting for incoming connection on 192.168.33.11:2000
Aug 13 17:14:20.751285 [145661] *ERROR* peer.c: 173: rpma_peer_mr_reg: ibv_reg_mr() failed: Invalid argument
```
With devdax:
```
[vagrant@node2 03-read-to-persistent]$ ./server 192.168.33.11 2000 /dev/dax0.0 
Aug 13 17:18:14.091100 [145686] *NOTE*  ep.c:  92: rpma_ep_listen: Waiting for incoming connection on 192.168.33.11:2000
Aug 13 17:18:14.091125 [145686] *ERROR* peer.c: 173: rpma_peer_mr_reg: ibv_reg_mr() failed: Invalid argument
```
dmesg output:
```
[384339.219335] rdma_rxe: err -12 from rxe_umem_get
```
I have no clue what is wrong, could you suggest me a working virtual setup for rpma?

**Comment by yangx-jy** [comment]
The `-12` means `ENOMEM 12 /* Out of memory */`, could you provide more info? for example:
1) the detailed setting of memmap option
2) the size of the device (devdax and pmem)
3) the usage of the local dram (used, free)

By the way, current rxe doesn't support fsdax mode.

**Comment by baru64** [comment]
@yangx-jy 

The VM's are configured with 3072M memory. I've tried memmap settings: `memmap=512M!1536M` and `memmap=256M!2560M`.
Usage of dram for 256M version:
```
[vagrant@node1 03-read-to-persistent]$ free -m
               total        used        free      shared  buff/cache   available
Mem:            2719         180        2314           0         224        2391
Swap:           2718           0        2718
```
Creating namespace with devdax mode:
```
[vagrant@node1 ~]$ sudo ndctl create-namespace --reconfig namespace0.0 --mode devdax --force
{
  "dev":"namespace0.0",
  "mode":"devdax",
  "map":"dev",
  "size":"250.00 MiB (262.14 MB)",
  "uuid":"d66544d3-a92c-4d15-b96e-4de3828301b7",
  "daxregion":{
    "id":0,
    "size":"250.00 MiB (262.14 MB)",
    "align":2097152,
    "devices":[
      {
        "chardev":"dax0.0",
        "size":"250.00 MiB (262.14 MB)",
        "target_node":0,
        "align":2097152,
        "mode":"devdax"
      }
    ]
  },
  "align":2097152
}
[vagrant@node1 03-read-to-persistent]$ ls -l /dev/dax*
crw-rw-rw-. 1 vagrant vagrant 252, 3 08-16 16:38 /dev/dax0.0
```
I'm running example/03-read-to-persistent without any changes.
I've also tested it on physical servers with Mellanox RNICs and Intel Optane and got the same error, server has 182G DRAM and 177G devdax namespace.

**Comment by yangx-jy** [comment]
Hi @baru64 

Thanks, could you provide the output of `ulimit -a`?

**Comment by baru64** [comment]
@yangx-jy 
Thank you, It looks like the limit was causing the error. After `ulimit -l unlimited` I can run the examples :)

I will close this issue since it's resolved.
