### ISSUE TITLE
Deprecate the `rpma_conn_completion_*()` functions

### ISSUE THREAD

**Issue by janekmi** [pmem/rpma#1212]
When #1080 will be merged it effectively makes a number of functions obsolete:

- `rpma_conn_completion_get()`
- `rpma_conn_completion_wait()`
- `rpma_conn_get_completion_fd()`

Currently, we think the right thing to do is to:

1. Mark these functions as deprecated.
2. Delete them overall before the release after next.

**NOTE**: Along with marking these functions as deprecated, it will be helpful to add to the librpma(7) a note on how the end-user should interpret such a notice.

**Comment by yangx-jy** [comment]
Hi @janekmi @grom72 @ldorau 

Should I update all examples to use the new APIs?

**Comment by grom72** [comment]
Yes, we should be prepared for deprecated API to be removed.

**Comment by yangx-jy** [comment]
> Yes, we should be prepared for deprecated API to be removed.

OK, I will update all examples to use the new APIs this week.

**Comment by grom72** [comment]
Fixed in #1529
