### ISSUE TITLE
tools: perf: handle skips properly

### ISSUE THREAD

**Issue by janekmi** [pmem/rpma#1292]
In the current implementation, the `rpma_fio_bench.sh` and `ib_read.sh` scripts return 0 on skip which for `rpma_bench.py` is indistinguishable from successfully completing the scheduled benchmark.

One of the possible solutions is to introduce a dedicated return value for skips which will be handled by `rpma_bench.py` properly.

Ref: https://github.com/pmem/rpma/blob/master/tools/perf/bench_common.sh#L232

**Comment by ldorau** [comment]
The bash framework was removed in https://github.com/pmem/rpma/pull/1521
