### ISSUE TITLE
test: make common mocks common

### ISSUE THREAD

**Issue by janekmi** [pmem/rpma#134]
Currently, all mocks requires for a certain unit test is delivered in the same C-file. This approach introduces some unneeded redundancy. Please, investigate the possibility of making at least some of the mocks common for all unit tests which are using them.

**Comment by grom72** [comment]
- malloc

**Comment by janekmi** [comment]
It took some time but it seems we have already achieved this goal. All mocks for unit tests are common. It seems there is no point in making a single common mocks for both unit and integration tests. So for now I consider this effort finished.
