### ISSUE TITLE
Add LGTM.com security analysis to pmem/rpma

### ISSUE THREAD

**Issue by ldorau** [pmem/rpma#1411]
Add LGTM.com security analysis:

https://lgtm.com/help/lgtm/about-lgtm

 to pmem/rpma

**Comment by ldorau** [comment]
See: https://github.community/t/lgtm-how-to-install-packages-from-sources-sudo-does-not-work/223164

**Comment by grom72** [comment]
LGTM.com will be shut down in December 2022. It is recommended to use GitHub code scanning instead. 
https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/
