### ISSUE TITLE
Is it possible to develop rpma without Persistent Memory hardware? Any document guide?

### ISSUE THREAD

**Issue by changchengx** [pmem/rpma#1591]

**Comment by osalyk** [comment]
You can create an emulated environment.
https://pmem.io/blog/2016/02/how-to-emulate-persistent-memory/

**Comment by changchengx** [comment]
@osalyk Thanks for your info. I'll check it and feedback to you later.

**Comment by grom72** [comment]
@changchengx can we close this issue?
