### ISSUE TITLE
a wrong offset in read-after-write in 04-example

### ISSUE THREAD

**Issue by GrayXu** [pmem/rpma#1665]
https://github.com/pmem/rpma/blob/deb780969c2a1f8e37626758f89f7035aff5dc80/examples/04-write-to-persistent/client.c#L236-L237

> "... For flushing the posted write, it reads eight bytes from the same remote buffer to a local read-after-write DRAM buffer. ..."

raw_mr will read the `SIGNATURE_STR` part instead of remote buffer, as result this read won't flush the writes.

It should be:
```
ret = rpma_read(conn, raw_mr, 0, dst_mr, dst_offset, 8,
			RPMA_F_COMPLETION_ALWAYS, NULL);
```

**Comment by grom72** [comment]
We do not need to read what has been written. 
The read operation goal is to flush all buffers in the data path (PCIe, RDMA).
``SIGNATURE_STR`` is located in PMem so it should work properly.

**Comment by GrayXu** [comment]
Thanks for you reply  
Do you mean that a READ to any location of the PM can flush dirty data from the cache (*like RDMA NIC cache*)?

**Comment by GrayXu** [comment]
I found the reference. Thanks again.  
["RDMA Read address and length does not matter"](https://www.intel.com/content/www/us/en/developer/articles/technical/persistent-memory-replication-over-traditional-rdma-part-1-understanding-remote-persistent.html#:~:text=RDMA%20Read%20address%20and%20length%20does%20not%20matter)
