### ISSUE TITLE
question about example 05-flush-to-persistent

### ISSUE THREAD

**Issue by xywoo-cs** [pmem/rpma#1691]
`rpma_mr_write()` is based on one-sided verbs, as a result, we need **another request** to make sure the writtern data is persistent ( just like 04-write-to-persistent in the ARRM/APM style

But what's the fundamental difference between `rpma_read` and `rpma_flush` to ensure persistence? I found `rpma_flush_apm_new()` also uses read-after-write.

And what's the difference between `RPMA_MR_USAGE_FLUSH_TYPE_VISIBILITY` and `RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT`?

I thought a following READ will flush the written data to iMC, and all of them shoule be persistent and have visibility.

Thanks so much!

**Comment by grom72** [comment]
Hi @xywoo-cs,
``rpma_read()`` shows how to implement flush on the top of the existing RDMA stack while ``rpma_flush`` is a long-term support API that will not change when new RDMA ibv_wr_rdma_flush() is available in libibverbs.
``RPMA_MR_USAGE_FLUSH_TYPE_VISIBILITY`` and ``RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT`` are defined to support new types of flushes as defined in IBTA spec:
https://www.infinibandta.org/wp-content/uploads/2021/08/IBTA-Overview-of-IBTA-Volume-1-Release-1.5-and-MPE-2021-08-17-Secure.pptx.
https://cw.infinibandta.org/wg/LWG/document/8581

**Comment by xywoo-cs** [comment]
I get it. Thanks again!
