### ISSUE TITLE
numactl: execution of `fio': No such file or directory

### ISSUE THREAD

**Issue by DanielLee343** [pmem/rpma#1742]
Hi, I have this wired problem can't solve for days. I was doing the performance test with the provided script, when the "tool" tag in "series" is "fio", the stderr prompts this error:
`numactl: execution of `fio': No such file or directory
Although I believe fio is successfully installed and can be executed normally.
Could you provided some help? Can't thank you enough!

**Comment by osalyk** [comment]
Hi, you can specify the path to the fio binaries (on the local node - FIO_PATH, and on the remote node - REMOTE_FIO_PATH).
You can find more information in the [CONFIG.JSON.md](https://github.com/pmem/rpma/blob/master/tools/perf/CONFIG.JSON.md) file.

**Comment by DanielLee343** [comment]
Thanks, I'll close the issue!
