### ISSUE TITLE
No device found Error

### ISSUE THREAD

**Issue by lonnietc** [pmem/rpma#1934]
Hello,

I just build the rpma library and examples on my Ubuntu 20.04 (64-bit) system and all seems to have built fine. Then I did "make test" and all tests passed, but when I try to run an example, I get:

```
/rpma/build/examples/01-connection$ ./server 127.0.0.1 9000

Jul 21 18:01:43.916925 [524227] *ERROR* info.c:  63: rpma_info_new: rdma_getaddrinfo(node=127.0.0.1, service=(null), ai_flags=passive, ai_qp_type=IBV_QPT_RC, ai_port_space=RDMA_PS_TCP): No such device
```

I ran it as a user and as sudo but still the same results.

In the reading, I thought that the library falls back on web sockets if some special dma hardware is not found, but I am not sure on this part.

Any ideas as to what is happening?

**Comment by osalyk** [comment]
I see that you are using loopback (127.0.0.1), you need to configure the physical interface. 
I recommend reading the [DEVELOPMENT.md](https://github.com/pmem/rpma/blob/master/DEVELOPMENT.md) document.
In the [Testing](https://github.com/pmem/rpma/blob/master/DEVELOPMENT.md#preparing-the-environment) chapter you will find information on how to prepare the environment for operation.

**Comment by ldorau** [comment]
The loopback (127.0.0.1) will never work.

**Comment by lonnietc** [comment]
I actually tried it with:

```
$ cd /IntelLabs/rpma/build/examples/01-connection

./server 192.168.0.103 9000
```

but got the same result

```
Jul 22 12:13:59.120092 [530129] *ERROR* info.c:  63: rpma_info_new: rdma_getaddrinfo(node=192.168.0.103, service=(null), ai_flags=passive, ai_qp_type=IBV_QPT_RC, ai_port_space=RDMA_PS_TCP): No such device
```

I'm testing on one node of:

Dell PowerEdge C6220 SFF 4 Node Server 8x Xeon E5-2650 256GB RAM 4x 2TB 2.5" HD system

**Comment by ldorau** [comment]
See: https://github.com/pmem/rpma/blob/master/DEVELOPMENT.md#preparing-the-environment
1) Do you have a correctly configured RDMA-capable network interface (SoftRoCE or RDMA HW) with an IP address assigned?
2) Is it SoftRoCE or RDMA HW?
3) What is the output of the following command?:
```sh
$ [rpma]$ ./tools/config_softroce.sh
```

**Comment by ldorau** [comment]
@lonnietc Has the issue been solved?

**Comment by ldorau** [comment]
No answer, closing.
