### ISSUE TITLE
What's about adding rules to create software package, such as debian format?

### ISSUE THREAD

**Issue by changchengx** [pmem/rpma#239]

**Comment by janekmi** [comment]
I think it will be handy. I will add it to our plans so it will be implemented soon.

**Comment by janekmi** [comment]
The packaging is now up and running. It is also integrated into our CI.
@changchengx please verify if the solution works for you.

Ref: #299

**Comment by changchengx** [comment]
Build steps:
```
$ git clone https://github.com/pmem/rpma.git
$ cd rpma
$ git rev-parse HEAD
bdbcb68b6868c458889dcc23287786c25c99c217
$ mkdir build
$ cd build
$ cmake .. -DCPACK_GENERATOR='DEB' -DCMAKE_INSTALL_PREFIX=/usr
$ make package
```

Error log:
```
Error: current list of manuals(3) does match the file: /tmp/rpma/doc/manuals_3.txt
1d0
< librpma.7
Error: current list of manuals(7) does match the file: /tmp/rpma/doc/manuals_7.txt
In order to fix it, run 'make doc-fix'

make[2]: *** [doc/CMakeFiles/doc.dir/build.make:57: doc/CMakeFiles/doc] Error 1
make[1]: *** [CMakeFiles/Makefile2:2948: doc/CMakeFiles/doc.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by janekmi** [comment]
@changchengx please check how it works now.

**Comment by changchengx** [comment]
@janekmi I'll feedback the result after China National holiday

**Comment by changchengx** [comment]
@janekmi 
Build Steps:
```
$ git clone https://github.com/pmem/rpma.git
$ cd rpma/
$ git rev-parse HEAD
0b1f3b33fc28711b7a91eaf897e4951fd10528e5
$ mkdir build
$ cd build
$ cmake .. -DCPACK_GENERATOR='DEB' -DCMAKE_INSTALL_PREFIX=/usr
$ make package
```
Error Log:
```
[ 91%] Built target example-02-read-to-volatile
Scanning dependencies of target doc
src2man: errors found in the "rpma/src/include/librpma.h" file:
make[2]: *** [doc/CMakeFiles/doc.dir/build.make:57: doc/CMakeFiles/doc] Error 1
make[1]: *** [CMakeFiles/Makefile2:3148: doc/CMakeFiles/doc.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by ldorau** [comment]
@changchengx Does this issue still occurs for you?
`make package` is tested in every build:
https://github.com/pmem/rpma/blob/master/utils/docker/run-build.sh#L226
and it works on all distros listed here:
https://github.com/pmem/rpma/actions/runs/409459517
(https://github.com/pmem/rpma/actions?query=workflow%3ANightly)

1) What Linux distro and version are you running?
2) Please attach the whole log

**Comment by changchengx** [comment]
@ldorau 
I send the ```1) os info 2) build steps 3) build logs ``` to your mailbox.

BTW, do you know how to attach the log file in Github comment?

**Comment by changchengx** [comment]
@janekmi @ldorau 
This issue could be closed now.
The debian package build failure is because that txt2man version is 1.6.0-6 instead of >=1.7 on my build server.
The debian package could be built out after following below script to upgrade txt2man:
https://github.com/pmem/rpma/blob/master/utils/docker/images/install-txt2man.sh

**Comment by ldorau** [comment]
OK, thanks @changchengx for your feedback. Closing.
