### ISSUE TITLE
Package 'libibverbs', required by 'virtual:world', not found

### ISSUE THREAD

**Issue by janekmi** [pmem/rpma#289]
Your RPMA build may fail with the following or similar output:

```
-- Checking for module 'libibverbs>=1.0'
--   Package 'libibverbs', required by 'virtual:world', not found
CMake Error at /usr/local/share/cmake-3.18/Modules/FindPkgConfig.cmake:545 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18/Modules/FindPkgConfig.cmake:733 (_pkg_check_modules_internal)
  CMakeLists.txt:105 (pkg_check_modules)
```

It may be caused by two possible situations:
1. The dev(el) package is not installed in the system
2. The dev(el) package does not provide pkg-config files

# Solution 1.

You can verify if the dev(el) package is installed using this or similar command:

```bash
$ dnf list installed | grep 'rdma\|verbs'
libibverbs.x86_64                            16.2-3.fc28                     @fedora
librdmacm.x86_64                             16.2-3.fc28                     @fedora
rdma-core.x86_64                             16.2-3.fc28                     @fedora
rdma-core-devel.x86_64                       16.2-3.fc28                     @fedora
```

If you have libibverbs-devel or rdma-core-devel on the list above you can jump right to Solution 2.
Otherwise, you have to install one of the following packages:
- rdma-core-dev(el) OR
- libibverbs-dev(el) OR
- OFED provided by your RNIC manufacturer

# Solution 2.

You can verify if the dev(el) package is installed as follows:

```bash
$ ls -l /usr/lib64/pkgconfig/ | grep verbs
-rw-r--r--. 1 root root 379 08-17 16:38 libibverbs.pc
```

If you have on the list above libibverbs.pc file but still experiencing the issue please contact us.
Otherwise, your system is not yet supported by the RPMA build system. The RPMA team have identified the problem and we will prepare the required enhancements soon. Please stay tuned for the updates.

In the meantime, a workaround for the issue is to manually copy the libibverbs.pc and librdmacm.pc files to /usr/lib64/pkgconfig on the system. This workaround is not seamless. May not work for all systems or may require manual changes to the contents of the *.pc files.

[pc_issue.zip](https://github.com/pmem/rpma/files/5117200/pc_issue.zip)

# Note

For the simplicity sake, I have called development packages as dev(el). Whereas some Linux distributions provide them as dev packages (e.g. libibverbs-dev) and other as devel packages (e.g. libibverbs-devel).

# Acknowledgement

Thank you @graceleeis for reporting this issue.

# References

- linux-rdma/rdma-core#373 - Generate and install pkgconfig files for the RDMA libraries (the *.pc files are available from rdma-core v20.1)
- ofiwg/libfabric#2070 - verbs provider needs to strengthen libibverbs link check
- https://github.com/a-ilango/libfabric/commit/f3ba38283694c66750843136ccb1988ef4a5c79c - verbs: Strengthen configure check to workaround libtool behavior

**Comment by ldorau** [comment]
@graceleeis what Linux distribution/version did you encounter this issue on?

**Comment by janekmi** [comment]
An inspiration for publishing this issue was the observation no.2 (the dev(el) package does not provide pkg-config files).

For the first time, it was identified on Fedora 29. Which may or may not be important since the issue happened using Mellanox OFED 4.7-3.2.9.0-fc29 (which is prepared for a specific distribution and release but it is distributed separately). But the issue also occurs when rdma-core-devel packages are used. Fedora 29 currently provides 16.2-3.fc28 build of this package. Quick lookup shows this package does not provide *.pc files at the same time providing e.g. a regular set of *.h files.

```bash
$ rpm -ql rdma-core-devel | grep \\.pc
$ # no *.pc files provided
$ rpm -ql rdma-core-devel | grep \\.h
/usr/include/infiniband/acm.h
/usr/include/infiniband/acm_prov.h
/usr/include/infiniband/arch.h
/usr/include/infiniband/cm.h
/usr/include/infiniband/cm_abi.h
/usr/include/infiniband/ib.h
/usr/include/infiniband/kern-abi.h
/usr/include/infiniband/mlx4dv.h
/usr/include/infiniband/mlx5dv.h
/usr/include/infiniband/opcode.h
/usr/include/infiniband/sa-kern-abi.h
/usr/include/infiniband/sa.h
/usr/include/infiniband/tm_types.h
/usr/include/infiniband/umad.h
/usr/include/infiniband/umad_cm.h
/usr/include/infiniband/umad_sa.h
/usr/include/infiniband/umad_sa_mcm.h
/usr/include/infiniband/umad_sm.h
/usr/include/infiniband/umad_str.h
/usr/include/infiniband/umad_types.h
/usr/include/infiniband/verbs.h
/usr/include/rdma/rdma_cma.h
/usr/include/rdma/rdma_cma_abi.h
/usr/include/rdma/rdma_verbs.h
/usr/include/rdma/rsocket.h
```

For comparison rdma-core-devel-20.1-3.fc30 (provided for Fedora 30) has *.pc files ([source](https://fedora.pkgs.org/30/fedora-x86_64/rdma-core-devel-20.1-3.fc30.x86_64.rpm.html)).

Which makes perfect sense since the *.pc files are available from rdma-core v20.1. Please see the reference above.

**Comment by janekmi** [comment]
@graceleeis please verify if the solution works for you.

**Comment by ldorau** [comment]
> @graceleeis please verify if the solution works for you.

@graceleeis ?

**Comment by ETaradayko** [comment]
Hi guys,
Do you support Centos 9 stream?

**Comment by ldorau** [comment]
We used to, but we have stopped, because there is no official docker image of CentOS Stream.
See: 
https://github.com/pmem/rpma/blob/main/.github/workflows/nightly_experimental.yml#L38-L40
https://hub.docker.com/_/centos

However we still have a Dockerfile for CentOS Stream in the repo:
https://github.com/pmem/rpma/blob/main/utils/docker/images/Dockerfile.centos-stream

**Comment by ldorau** [comment]
@ETaradayko What problem do you have? Did you get the "_Package 'libibverbs', required by 'virtual:world', not found_" error?

**Comment by ldorau** [comment]
@ETaradayko We support Rocky Linux 9, so it should not be difficult to make CentOS 9 Stream work as well.

**Comment by ldorau** [comment]
We used to, but we stopped on Mar 1, 2022 (https://github.com/pmem/rpma/commit/946c8d2d1b50350329bb628729df5cc2c2d5a14f) because there is no official docker image of CentOS Stream, see:
https://github.com/pmem/rpma/blob/main/.github/workflows/nightly_experimental.yml#L38-L40
https://hub.docker.com/_/centos

However we still have a Dockerfile for CentOS Stream in the repo, but it may not work since it has not been run nor validated from a long time: https://github.com/pmem/rpma/blob/main/utils/docker/images/Dockerfile.centos-stream

We support Rocky Linux 9, so it should not be difficult to make CentOS 9 Stream work as well.

@ETaradayko What problem do you have? Did you get the "Package 'libibverbs', required by 'virtual:world', not found" error?
