### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by karczex** [pmem/rpma#408]
* Please add parameters descriptions of all functions to man pages. 

i.e. it's pretty hard to figure out if rpma_conn_private_data pointer passed to rpma_conn_get_private_data() may be NULL or not. 

* Error 404:
    http://pmem.io/rpma/master/rpma_peer_cfg_get_persistent_flush_supported.3
    http://pmem.io/rpma/master/rpma_peer_cfg_set_auto_flush.3
    http://pmem.io/rpma/master/rpma_peer_cfg_set_ddio.3

* XXX in error list http://pmem.io/rpma/master/rpma_conn_apply_remote_peer_cfg.3

* No description in some methods. i.e. http://pmem.io/rpma/master/rpma_conn_cfg_get_cq_size.3

**Comment by janekmi** [comment]
It seems all of these are now done well. Closing.
