### ISSUE TITLE
INSTALL.md to describe librpma dev environment

### ISSUE THREAD

**Issue by grom72** [pmem/rpma#42]
It will be very useful to have a separate file to describe how to prepare development environment for librpma.
An example is here: https://gitlab.com/cmocka/cmocka/-/blob/master/INSTALL.md

- cmake ver ??? installation
- libibverbs-dev installation
- librdmacm-dev installation
- cmocka installation -> insyall_cmocka.sh
- libunwind-dev installation 
- valigrind installation -> install_valgrind.sh
- txt2man installation -> install_txt2man.sh
- sudo apt install groff

**Comment by janekmi** [comment]
We have now [INSTALL.md](https://github.com/pmem/rpma/blob/master/INSTALL.md) in our repo. In case you will see any missing pieces there please let us know.
