### ISSUE TITLE
make doc does not work

### ISSUE THREAD

**Issue by lukaszstolarczuk** [pmem/rpma#434]
I run `make doc` on current master (a38e166) and it does not work.

```
Error: current list of manuals(3) does match the file: /tmp/rpma/doc/manuals_3.txt
1d0
< librpma.7
Error: current list of manuals(7) does match the file: /tmp/rpma/doc/manuals_7.txt
In order to fix it, run 'make doc-fix'
```

I'm working on clean, just downloaded repo: see [full_log.txt](https://github.com/pmem/rpma/files/5268878/full_log.txt)

**Comment by ldorau** [comment]
@lukaszstolarczuk It is very, very strange... `make all` depends on `make doc` , so it is run in every CI build, so - as you can easily check - it generally works, also for the a38e166 commit:
https://github.com/pmem/rpma/actions/runs/266641929
and:
https://travis-ci.org/github/pmem/rpma/builds/729254975

It also works on my dev machine at this commit. 
I have exactly repeated your steps on my machine on the current master (9d4e23d) and I cannot reproduce it ...

**Comment by lukaszstolarczuk** [comment]
hmm.. maybe the dependencies :/ I just saw that you require very specific version of txt2man (I have 1.6.0)

I'll double-check this and update the issue.

**Comment by janekmi** [comment]
Your log file indicates pretty clearly that your version of src2man cannot handle our documentation properly.
It seems you have missed this line of our [INSTALL.md](/pmem/rpma/blob/master/INSTALL.md) file:

> txt2man == 1.7.0 (please see https://github.com/pmem/rpma/blob/master/utils/docker/images/install-txt2man.sh to install the verified revision)

Please verify if it works for you.

**Comment by lukaszstolarczuk** [comment]
Verified with proper txt2man - works correctly on `0.9.0-rc1`
