### ISSUE TITLE
`make config_softroce` fails when rdma link add is not implemented

### ISSUE THREAD

**Issue by janekmi** [pmem/rpma#560]
## Issue
The [config_softroce.sh](https://github.com/pmem/rpma/blob/master/examples/config_softroce.sh) script assumes that if `rdma` command is available in the system it has implemented `rdma link add` command. Which is not true for all `rdma` releases. e.g. `rdma` binary from [rdma-core-devel-22.4-4.el7_8](https://centos.pkgs.org/7/centos-updates-x86_64/rdma-core-devel-22.4-4.el7_8.x86_64.rpm.html) from CentOS 7.8 does not provide this command. It only implements `rdma link show` command.

## A possible solution
Use good old `rxe_cfg` as a fallback in case `rdma` is not available in the system or `rdma link add` is not implemented.

**Comment by yangx-jy** [comment]
Hi,

How about using /sys/module/rdma_rxe/parameters/{add, remove} interfaces directly?
In this way, we only create IB interface name with fixed format(e.g. rxe0, rxe1) but we don't depend any command(e.g. old rxe_cfg or new rdma link).

Best Regards,
Xiao Yang

**Comment by ldorau** [comment]
> Hi @janekmi
> 
> How about using /sys/module/rdma_rxe/parameters/{add, remove} interfaces directly?
> In this way, we only create IB interface name with fixed format(e.g. rxe0, rxe1) but we don't depend any command(e.g. old rxe_cfg or new rdma link).
> 
> Best Regards,
> Xiao Yang

Hi @yangx-jy, using sysfs (/sys/module/rdma_rxe/parameters/{add, remove}) one can only add or remove an interface,
but I cannot find a way to check or list already configured interfaces. Do you know how to do that?

**Comment by ldorau** [comment]
@yangx-jy What OS-version do you use that does not have the `rdma show link` command?

**Comment by yangx-jy** [comment]
> Hi @yangx-jy, using sysfs (/sys/module/rdma_rxe/parameters/{add, remove}) one can only add or remove an interface,
> but I cannot find a way to check or list already configured interfaces - that what `rdma link show` does. Do you know how to do that?
Hi @ldorau 
I think we can check or list already configured interfaces by scanning /sys/class/infiniband/*.

**Comment by ldorau** [comment]
> > Hi @yangx-jy, using sysfs (/sys/module/rdma_rxe/parameters/{add, remove}) one can only add or remove an interface,
> > but I cannot find a way to check or list already configured interfaces - that what `rdma link show` does. Do you know how to do that?
> 
> Hi @ldorau
> I think we can check or list already configured interfaces by scanning /sys/class/infiniband/*.
> 

OK, but how to verify its parameters? - how to check whether `state ACTIVE physical_state LINK_UP`) ?

**Comment by yangx-jy** [comment]
> 
> 
> > > Hi @yangx-jy, using sysfs (/sys/module/rdma_rxe/parameters/{add, remove}) one can only add or remove an interface,
> > > but I cannot find a way to check or list already configured interfaces - that what `rdma link show` does. Do you know how to do that?
> > 
> > 
> > Hi @ldorau
> > I think we can check or list already configured interfaces by scanning /sys/class/infiniband/*.
> 
> OK, but how to verify its parameters? - how to check whether `state ACTIVE physical_state LINK_UP` ?

How about reading the following files?
```
# pwd
/sys/class/infiniband/rxe_enp2s0
# find ./ -name '*state*'
./ports/1/state
./ports/1/phys_state
# cat ./ports/1/state
4: ACTIVE
# cat ./ports/1/phys_state
5: LinkUp
```

**Comment by ldorau** [comment]
Yeah, I see it is possible, but with so much parsing sysfs it becomes more and more complicated ...

**Comment by yangx-jy** [comment]
> 
> 
> Yeah, I see it is possible, but with so much parsing sysfs it becomes more and more complicated ...

Yes.  It is more complicated and there is another worry here.
Current sysfs only creates IB interface name with fixed format(e.g. rxe0, rxe1)  so it cannot create custom name as rdma link add does.   Perhaps, we need to keep sysfs and rdma link consistent by improving sysfs.

**Comment by ldorau** [comment]
@janekmi It seems `rxe_cfg` has a bug - it does not print out `RDEV` although it is configured:
```
$ sudo rdma link show
0/1: rxe_wlp9s0u1/1: state ACTIVE physical_state LINK_UP 

$ sudo rxe_cfg status
  Name  Link  Driver  Speed  NMTU  IPv4_addr   RDEV  RMTU  
  eth0  yes   veth           1500  172.17.0.2              
```
and their output is not very compatible ...

**Comment by yangx-jy** [comment]
> 
> 
> @janekmi It seems `rxe_cfg` has a bug - it does not print out `RDEV` although it is configured:
> 
> ```
> $ sudo rdma link show
> 0/1: rxe_wlp9s0u1/1: state ACTIVE physical_state LINK_UP 
> 
> $ sudo rxe_cfg status
>   Name  Link  Driver  Speed  NMTU  IPv4_addr   RDEV  RMTU  
>   eth0  yes   veth           1500  172.17.0.2              
> ```
> 
> and their output is not very compatible ...

Hi @ldorau 

rxe_cfg has been removed by rdma-core since 2020.2.3.  I think It is unnecessary fix the deprecated rxe_cfg, right?

By the way, do you want to resolve #560 by using either rxe_cfg or rdma link?
In this case, it seems still depends on different package version, and I perfer to use sysfs directly.

Best Regards,
Xiao Yang
