### ISSUE TITLE
sprintf tests fail with -D_FORTIFY_SOURCE=2

### ISSUE THREAD

**Issue by kilobyte** [pmem/rpma#561]
When running tests build with `-O2 -D_FORTIFY_SOURCE=2` (included in Debian's default flags for building packages), sprintf/syslog/stderr tests fail with errors such as:
* %s() has remaining non-returned values.
* '%s' parameter still has values that haven't been checked.

Doesn't reproduce with -O0.

```
-- Stderr:
[  ERROR   ] --- %s() has remaining non-returned values.
/home/kilobyte/c/rpma/tests/unit/log_default/function.c:107: note: remaining item was declared here

[  ERROR   ] --- %s() has remaining non-returned values.
/home/kilobyte/c/rpma/tests/unit/log_default/function.c:122: note: remaining item was declared here
%s() has remaining non-returned values.
/home/kilobyte/c/rpma/tests/unit/log_default/function.c:123: note: remaining item was declared here
%s() has remaining non-returned values.
/home/kilobyte/c/rpma/tests/unit/log_default/function.c:124: note: remaining item was declared here
syslog: '%s' parameter still has values that haven't been checked.
/home/kilobyte/c/rpma/tests/unit/log_default/function.c:125: note: remaining item was declared here
'%s' parameter still has values that haven't been checked.
/home/kilobyte/c/rpma/tests/unit/log_default/function.c:132: note: remaining item was declared here
```
plus many more of the above.

As you use a weird mocking library with many layers of indirection, it wasn't obvious to me where's the actual call, thus I'll let you take a look first before digging deeper.

**Comment by ldorau** [comment]
@kilobyte please test the fix: #582

**Comment by pbalcer** [comment]
* workaround

It's not a fix ;)

**Comment by ldorau** [comment]
This is a workaround fixing this issue ;-P

**Comment by ldorau** [comment]
@kilobyte workaround merged ;-)

**Comment by kilobyte** [comment]
That's indeed not a fix, but it indeed works.

**Comment by ldorau** [comment]
@kilobyte thanks for testing

**Comment by ldorau** [comment]
@pbalcer @kilobyte 

The `log_default` test requires mocking the following '`*printf`' functions: `vsnprintf, snprintf` and `fprintf`,
but the `-D _FORTIFY_SOURCE=2` option replaces the original `*printf` functions with different ones
and causes our mocks of those functions to not work, so the `log_default` test just cannot work
with the `-D _FORTIFY_SOURCE=2` option set, so there is no fix for this issue except of disabling this test.

Please see also: https://github.com/pmem/rpma/blob/master/tests/unit/log_default/CMakeLists.txt#L10
