### ISSUE TITLE
mans_header.md assumes inside-tree build

### ISSUE THREAD

**Issue by kilobyte** [pmem/rpma#562]
A full build spams stderr with:
```
cat: ../../utils/mans_header.md: No such file or directory
```
This won't work unless you build from inside the tree, in a manually created subdir exactly one level deep.  Typical build scripts use a completely different dir.

Also, failure of the `cat` fails to fail the build.

**Comment by ldorau** [comment]
@kilobyte please review and test the fix: #583

**Comment by ldorau** [comment]
@kilobyte fix merged ;-)

**Comment by kilobyte** [comment]
Awesome — tested, works both in `${SRCDIR}/a/a` and in `/tmp/foo`

**Comment by ldorau** [comment]
@kilobyte thanks for testing
