### ISSUE TITLE
rpma vs RDMA with PMEM extension

### ISSUE THREAD

**Issue by ultra-nexus** [pmem/rpma#568]
Hi, as far as I know, the [IETF](https://tools.ietf.org/id/draft-talpey-rdma-commit-01.html) and [IBTA](https://cw.infinibandta.org/wg/Members/document/8594) are both planed to extend RDMA protocol to support persistent memory. Three new verbs including `flush/verify/atomic` will be introduced in the future. I want to know what is the difference between `rpma` and `RDMA with PMEM extensions`. If they are for the same purpose, will rpma be obsoleted after the `RDMA with PMEM extensions` is mature. Thanks.

**Comment by grom72** [comment]
Librpma is put on the top of libibverbs. The primary purpose of it is to simplify the integration process of end-user applications with RPMem. The librpma proposes a more memcpy-like API, while libibverbs API is a more communication-oriented one. The librpma will support all new verbs when they become available in the Linux software stack. Librpma API should work in the same way with or without the RDMA PMem extension implemented in libibverbs. Anyhow RPMem could be implemented directly on the top of libibverbs even now. We do not want to exchange libibverbs/librdmacm - we want to make it use easier.

**Comment by ultra-nexus** [comment]
Get it, thanks. Does this project have guidelines to contributors who are not employees of Intel. If we want to contribute to this project, where should we start.

**Comment by pbalcer** [comment]
You can find contributing guidelines in CONTRIBUTING.md in the repo.

At the moment, one of the best ways to contribute is to simply use the library and tell us your feedback about the functionality and APIs. If you find a missing functionality that you'd like to work on in the course of your research, please check the ROADMAP.md. If it's not there, feel free to file an issue, and we'd be more than happy to help you with your contribution.

**Comment by ultra-nexus** [comment]
Thanks!
