### ISSUE TITLE
CDDL license text is missing

### ISSUE THREAD

**Issue by kilobyte** [pmem/rpma#570]
The package has just been rejected from Debian because of missing license text of CDDL.

The only file under CDDL, `utils/cstyle`, includes the following header:
```
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
```

Both places listed in the license are gone:
* `usr/src/OPENSOLARIS.LICENSE` is not there on any Linux distro, and OpenSolaris itself is dead since 2010 (you can still obtain a fork, or the original in some dark corner of the Internet)
* www.opensolaris.org is down (and pretty obviously 410-compliant)

If we want to continue to ship this file, we'd need to obtain a copy of OPENSOLARIS.LICENSE and include it in our tree.

**Comment by kilobyte** [comment]
I wonder which version of CDDL should apply: 1.0 or 1.1?

The header doesn't specify one.  Based on the file's date, 1.0 is ok, but so is 1.1 — as it got shipped with OpenSolaris later on, and the header claims you can use usr/src/OPENSOLARIS.LICENSE without specifying a version.

**Comment by pbalcer** [comment]
I think the same applies to all of the PMDK projects - we use cstyle for everything except C++.
@andyrudoff do you know the answer to @kilobyte question? If we knew which specific license version this needs, then we could replace the entire text with SPDX license identifier, and that would hopefully solve the problem.

**Comment by pbalcer** [comment]
Ok, Andy said that cstyle was taken from illumos, so this is the license to which that text is referring to:
https://github.com/illumos/illumos-gate/blob/master/usr/src/OPENSOLARIS.LICENSE

This is CDDL 1.0, so my vote is to use SPDX id, CDDL-1.0.
