### ISSUE TITLE
How to make two flush types(RPMA_FLUSH_TYPE_PERSISTENT/RPMA_FLUSH_TYPE_VISIBILITY) work?

### ISSUE THREAD

**Issue by yangx-jy** [pmem/rpma#578]
Hi, 

It seems that two flush types(RPMA_FLUSH_TYPE_PERSISTENT/RPMA_FLUSH_TYPE_VISIBILITY) specified by rpma_flush() are not passed into rpma_mr_read()  and rpma_flush() just does RDMA read operation.  So I wonder how rpma_flush() makes these types take effect?

Best Regards,
Xiao Yang

**Comment by grom72** [comment]
Hi,
the librpma API is based on flush semantic proposed by IBTA.
Present RDMA implementation does not support yet two flush types both are implemented the same way wit RDMA Read verb. For details please see the following document:
https://software.intel.com/content/www/us/en/develop/articles/persistent-memory-replication-over-traditional-rdma-part-1-understanding-remote-persistent.html
Best Regards,
Tomasz
