### ISSUE TITLE
Let server to access a connection private data before the connection from a client is established 

### ISSUE THREAD

**Issue by grom72** [pmem/rpma#736]
Currently, the application running a server side (ep) does not have access to a connection private data until a connection is established.
In this case, the application does not have the possibility to tune the connection environment (memory regions, etc.) based on the peer application's data.
rpma_conn_private_data is already a part of rpma_con_req. But no interface makes them available for the application.

The proposal of the solution has been drafted in #646. 
The final solution should cover UT and an example.

**Comment by janekmi** [comment]
Ref: #911
