### ISSUE TITLE
C++ interfaces of RPMA

### ISSUE THREAD

**Issue by lixiaoy1** [pmem/rpma#738]
Ceph is in C++, and RPMA is in C. And can RPMA provide the same mechanism as PMDK so that we can call RPMA interfaces directly?
https://github.com/pmem/pmdk/blob/master/src/include/libpmemlog.h#L46

**Comment by janekmi** [comment]
@lixiaoy1 please verify #743 works for you.

**Comment by janekmi** [comment]
Confirmed offline.
