### ISSUE TITLE
mr_local API to give access to size and memory pointer

### ISSUE THREAD

**Issue by grom72** [pmem/rpma#870]
As a library user, I would like to have access to the raw memory pointer and size of registered memory so I do not need to pass them separately from function to function but could pass only mr_local pointer.

**Comment by yangx-jy** [comment]
Hi @grom72 

How about the following APIs:
```
struct rpma_mr_local;
int rpma_mr_get_size(struct rpma_mr_local *mr, size_t *size);
int rpma_mr_get_mm_ptr(struct rpma_mr_local *mr, void **mm_ptr);
```

Best Regards,
Xiao Yang

**Comment by grom72** [comment]
API looks ok, I only suggest removing ```mm_``` part from names.

**Comment by yangx-jy** [comment]
> 
> 
> API looks ok, I only suggest removing `mm_` part from names.

Hi @grom72 

Thanks for your comment.
I agree on removing 'mm_' part because it becomes simpler and clearer.

I will wait @janekmi @ldorau to review the PR.

Best Regards,
Xiao Yang

**Comment by janekmi** [comment]
It looks good. Thank you @yangx-jy for this effort!

**Comment by janekmi** [comment]
Ref: #925

**Comment by yangx-jy** [comment]
> 
> 
> Ref: #925

Hi @janekmi @ldorau 

Ping.

Best Regards,
Xiao Yang

**Comment by grom72** [comment]
Done
