### ISSUE TITLE
rai->ai_src_canonname and rai->ai_dst_canonname are always null 

### ISSUE THREAD

**Issue by yangx-jy** [pmem/rpma#909]
1) rai->ai_src_canonname in rpma_info_bind_addr() is always NULL.
2) rai->ai_src_canonname and rai->ai_dst_canonname in rpma_info_resolve_addr() are always NULL.

I am not sure how to make them show the correc IP address.
@janekmi @ldorau do you have any suggestion?

**Comment by yangx-jy** [comment]
1) rai->ai_src_canonname in rpma_info_bind_addr() is always NULL.
2) rai->ai_src_canonname and rai->ai_dst_canonname in rpma_info_resolve_addr() are always NULL.

I am not sure how to make them show the correc IP address.
@janekmi @ldorau do you have any suggestion?

**Comment by janekmi** [comment]
Do you still experience this issue?
Can you provide any details?
