### ISSUE TITLE
Current status about librpma

### ISSUE THREAD

**Issue by hao-lee** [pmem/rpma#94]
Hi, as librpmem has some pain points, I think librpma will be the core library to use RDMA with NVDIMM. I have glaced this repository and have found that it only implements several functions currently. Does this library have a roadmap or something like design documentation so I can follow its development or contribute to it. Thanks.

**Comment by janekmi** [comment]
Yes. We are aiming to implement all operations vital for remote persistent memory: read, write, flush just to mention a few.
We are planning to make our roadmap public in a few weeks.

If you identify anything we are lacking and what you consider generally useful feel free to reach us.

**Comment by hao-lee** [comment]
Thanks! Looking forward to the roadmap.

**Comment by grom72** [comment]
hao-l

**Comment by grom72** [comment]
Hi @hao-lee !
The actual roadmap is available in [ROADMAP.md](https://github.com/pmem/rpma/blob/master/ROADMAP.md) file

**Comment by hao-lee** [comment]
@grom72 Thanks!
