### ISSUE TITLE
Shared Receive Queue (SRQ)

### ISSUE THREAD

**Issue by janekmi** [pmem/rpma#958]
Just a place to discuss the API @ultra-nexus is working on.

Ref: #685
Ref: #783

**Comment by ultra-nexus** [comment]
Hi, my current implementation saves a srq pointer in `peer` struct and all connections based on this peer can use this SRQ.

**Comment by ultra-nexus** [comment]
I have fixed a big problem in my example-12. Now it's time to focus on the SRQ implementation. The current implementation can handle hundreds clients at the same time using one Shared Receive Queue. Any comments are welcome to improve my implementation. Thanks.

**Comment by janekmi** [comment]
This topic is tightly coupled to #737. There you can find the current proposition of the SRQ API: https://github.com/pmem/rpma/issues/737#issuecomment-812533154

**Comment by yangx-jy** [comment]
Hi,

I hope we can solve #979 and #1087 as soon as possible so that I can continue implementing the SRQ.

Best Regards,
Xiao Yang

**Comment by yangx-jy** [comment]
Hi @janekmi @grom72 @ldorau 

I am trying to implement SRQ based on Idea No3A:
```
/* a SRQ configuration structure */
struct rpma_srq_cfg;

int rpma_srq_cfg_new(struct rpma_srq_cfg **scfg_ptr);
int rpma_srq_cfg_delete(struct rpma_srq_cfg **scfg_ptr);

int rpma_srq_cfg_set_rq_size(struct rpma_srq_cfg *scfg, uint32_t rq_size);
// rcq_size == 0 means no CQ for receives is provided along with SRQ
int rpma_srq_cfg_set_rcq_size(struct rpma_srq_cfg *scfg, uint32_t rcq_size);

/* the SRQ itself */
struct rpma_srq;

// ibv_create_srq
int rpma_srq_new(struct rpma_peer *peer, struct rpma_srq_cfg *scfg, struct rpma_srq **srq_ptr);
int rpma_srq_delete(struct rpma_srq **srq_ptr);

// overwrites rpma_conn_cfg_set_rq_size()
int rpma_conn_cfg_set_srq(const struct rpma_conn_cfg *cfg, struct rpma_srq *srq);

int rpma_srq_recv(struct rpma_srq *srq, struct rpma_mr_local *dst, size_t offset, size_t len, const void *op_context);

int rpma_srq_get_rcq(const struct rpma_srq *conn, struct rpma_cq **cq_ptr);
```

I have a question about the design, how to pass `struct rpma_srq` object to `rpma_conn_req_new()/rpma_ep_next_conn_req()`?
Do you want to insert `struct rpma_srq` object into `struct rpma_conn_cfg` by `rpma_conn_cfg_set_srq()`?

**Comment by grom72** [comment]
I think this is the best what we can do now.
Otherwise, we have to touch many functions' signatures to pass SRQ separately.

**Comment by ldorau** [comment]
SRQ has been implemented by https://github.com/pmem/rpma/pull/1616
