### ISSUE TITLE
Undocummented `struct rpma_conn_cfg *` defualt values

### ISSUE THREAD

**Issue by janekmi** [pmem/rpma#978]
Currently, `struct rpma_conn_cfg` (in the near future probably also `struct rpma_srq_cfg`) provides some defaults for parameters which values should be known by the software developer e.g. size of CQ, SQ, RQ. Without defaults, these parameters will become required. It is very important to make this decision consciously because introducing a required parameter is a not backward compatible change. On the other hand, knowing the exact values of these parameters is required to write a non-trivial application using librpma.

Let's discuss.

**Comment by janekmi** [comment]
We agree that as long as the end-user will receive an error when a queue will be overrun it is not a problem.

**Comment by janekmi** [comment]
Still, it is a good idea to document that:

- when no `*cfg` is provided the default is used instead: https://pmem.io/rpma/manpages/master/rpma_conn_req_new.3
- when `struct rpma_conn_cfg *` is not modified it has the default values: https://pmem.io/rpma/manpages/master/rpma_conn_cfg_new.3

**Comment by Patryk717** [comment]
[done](https://github.com/pmem/rpma/pull/1537)

**Comment by Patryk717** [comment]
fixed by  https://github.com/pmem/rpma/pull/1537
