### ISSUE TITLE
Applying libpmem2 to librpma examples

### ISSUE THREAD

**Issue by osalyk** [pmem/rpma#991]
In the examples that use libpmem providing the mapping may be improved using the libpmem2 library. 
As an example, see https://github.com/pmem/pmdk/blob/master/src/examples/libpmem2/advanced/advanced.c
Using libpmem2 we can map exactly the area we need: 
- `pmem2_config_set_offset()`
- `pmem2_config_set_length()`

**Comment by haichangsi** [comment]
https://github.com/pmem/rpma/pull/1631
https://github.com/pmem/rpma/pull/1746
https://github.com/pmem/rpma/pull/1791
https://github.com/pmem/rpma/pull/1853
https://github.com/pmem/rpma/pull/1854
https://github.com/pmem/rpma/pull/1909
https://github.com/pmem/rpma/pull/1914
https://github.com/pmem/rpma/pull/1957
