### ISSUE TITLE
Applying libpmem2 to the librpma FIO engines

### ISSUE THREAD

**Issue by osalyk** [pmem/rpma#992]
Use the libpmem2 library.
As an example, see https://github.com/pmem/pmdk/blob/master/src/examples/libpmem2/advanced/advanced.c
Using libpmem2 we can map exactly the area we need: 
- `pmem2_config_set_offset()`
- `pmem2_config_set_length()`

Requires changes in Makefile and configure.

For changes related to librpma_apm_* and librpma_gpspm_* engines please use branch: https://github.com/pmem/fio/tree/rpma
For changes related to librpma_aof_* engine please use this branch: https://github.com/pmem/fio/tree/aof

**Comment by ldorau** [comment]
We have to wait with adding support for libpmem2 until it is included (as a package) in most of popular Linux distributions, so that fio does not require building and installing whole PMDK from sources (@lplewa @kilobyte).

**Comment by kilobyte** [comment]
libpmem2 is available since PMDK 1.10, and that's been available in distros for a while.

[Status table](https://pmdk.angband.pl/distros.pl).

**Comment by ldorau** [comment]
Done by: https://github.com/pmem/fio/pull/269 and https://github.com/pmem/fio/pull/279
